version 1.6.2

diff --git a/lib/mkdir b/lib/mkdir
--- a/lib/mkdir
+++ b/lib/mkdir
@@ -9,17 +9,17 @@ UNLINK_BYPASS="";
 me=$(whoami);
 reportmsg="mkdir";
 for item in "$@"; do
-	regex="^.*['[:space:]].*$";
-	if [[ "$item" =~ $regex ]]; then
-	    regex="^(.*=)(.*['[:space:]].*)$";
-	    if [[ "$item" =~ $regex ]]; then
-			reportmsg="$reportmsg ${BASH_REMATCH[1]}\"${BASH_REMATCH[2]}\"";
-		else
-			reportmsg="$reportmsg \"$item\"";
-		fi
-	else
-		reportmsg="$reportmsg $item";
-	fi
+    regex="^.*['[:space:]].*$";
+    if [[ "$item" =~ $regex ]]; then
+        regex="^(.*=)(.*['[:space:]].*)$";
+        if [[ "$item" =~ $regex ]]; then
+            reportmsg="$reportmsg ${BASH_REMATCH[1]}\"${BASH_REMATCH[2]}\"";
+        else
+            reportmsg="$reportmsg \"$item\"";
+        fi
+    else
+        reportmsg="$reportmsg $item";
+    fi
 done
 
 for p in $(type -ap mkdir) ; do
@@ -31,8 +31,15 @@ if [ -z "$DAISY_CHAIN" ]; then
   exit 1;
 fi
 
-if [[ $UID -eq 0 ]]; then
-  $DAISY_CHAIN "$@";
+error_code=0;
+#if [[ $UID -eq 0 ]]; then
+#  $DAISY_CHAIN "$@" || error_code="$?";
+#  exit $error_code; #pass back any error code
+#fi
+
+if [[ "$DISABLE_WRAPPERS" -eq 1 ]]; then
+  $DAISY_CHAIN "$@" || error_code="$?";
+  exit $error_code; #pass back any error code
 fi
 
 for p in $(type -ap unlink) ; do
@@ -51,43 +58,53 @@ item="";
 pass_error=0;
 pwd=$(pwd);
 error_code=0;
+existing_dir_error_code=0;
 audit_text="";
 
 report_filtered(){
-	echo 1>&2 "*** Filtered out setuid and/or setgid";
-	echo 1>&2 "*** See the $HOME/mkdir_filtered_options.txt file for details";
-	text="\n";
-	text="$text ------ Filtered out setuid and/or setgid ------\n";
-	text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
-	text="$text before: $(echo $reportmsg | sed  -e 's/%/%%/g')\n";
-	text="$text after: mkdir$options$(echo $escaped_files | sed  -e 's/%/%%/g')\n";
-	printf "$text" >>"$HOME/mkdir_filtered_options.txt";
+    echo 1>&2 "*** Filtered out setuid and/or setgid";
+    echo 1>&2 "*** See the $HOME/mkdir_filtered_options.txt file for details";
+    text="\n";
+    text="$text ------ Filtered out setuid and/or setgid ------\n";
+    text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
+    text="$text before: $(echo $reportmsg | sed  -e 's/%/%%/g')\n";
+    text="$text after: mkdir$options$(echo $escaped_files | sed  -e 's/%/%%/g')\n";
+    printf "$text" >>"$HOME/mkdir_filtered_options.txt";
 }
-
+report_errors(){
+    text="\n";
+    text="$text ------mkdir command syntax errors-------------\n";
+    text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
+    text="$text $(echo $reportmsg | sed  -e 's/%/%%/g')\n";
+    text="$text $1\n";
+    printf "$text" >>"$HOME/mkdir_syntax_errors.txt";
+}
 mkdir_audit_log(){
-	text="\n";
-	text="$text ------ original command -------------\n";
-	text="$text $(echo $reportmsg | sed -e 's/%/%%/g')\n";
-	text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
-	text="$text ------ one of the resulting commands actually run -------\n";
-	text="$text $1";
-	if [[ -n "$audit_text" ]]; then
-		text="$text error_code is: $error_code\n";
-		text="$text $(echo $audit_text | sed -e 's/%/%%/g')\n";
-		printf "$text" >>"$HOME/mkdir_errors.txt";
-	fi
-	# while debugging this wrapper you may want to uncomment the following line
-	#printf "$text" >>"$HOME/mkdir_audit.txt";
+    text="\n";
+    text="$text ------ original command -------------\n";
+    text="$text $(echo $reportmsg | sed -e 's/%/%%/g')\n";
+    text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
+    text="$text ------ one of the resulting commands actually run -------\n";
+    text="$text $1";
+    if [[ -n "$audit_text" ]]; then
+        text="$text error_code is: $error_code\n";
+        text="$text $(echo $audit_text | sed -e 's/%/%%/g')\n";
+        printf "$text" >>"$HOME/mkdir_errors.txt";
+    fi
+    if [[ "$ENABLE_WRAPPER_AUDIT" -eq 1 ]]; then
+        # log all mkdir commands actually run
+        printf "$text" >>"$HOME/mkdir_audit.txt";
+    fi
 }
 
 add_escaped_file(){
-	lastitem=$(echo "$item" | sed -e 's/\\/\\\\/g' -e 's/"/\\\\"/g');
-	regex="^.*['[:space:]].*$";
-	if [[ "$item" =~ $regex ]]; then
-		escaped_files="$escaped_files \"$item\"";
-	else
-		escaped_files="$escaped_files $item";
-	fi
+    lastitem=$(echo "$item" | sed -e 's/\\/\\\\/g' -e 's/"/\\\\"/g');
+    regex="^.*['[:space:]].*$";
+    if [[ "$item" =~ $regex ]]; then
+        escaped_files="$escaped_files \"$item\"";
+    else
+        escaped_files="$escaped_files $item";
+    fi
 }
 
 # Syntax
@@ -109,105 +126,106 @@ add_escaped_file(){
 # This for loop manages to process filenames or paths with white space or
 # special characters.
 for item in "$@"; do
-	if [[ $stopgettingoptions -eq 0 ]]; then
-		if [[ "$item" = '--' ]]; then
-			options="$options $item";
-			stopgettingoptions=1;
-			continue;
-		fi
-		# With options, spaces are assumed to delimit the options so we need
-		# continuation logic to process options that have been split with spaces.
-		if [[ $addnext -eq 1 ]];then
-			if [[ "$item" = '=' ]]; then
-				options="$options $item";
-			else
-				addnext=0;
-				options="$options $item";
-			fi
-			continue;
-		fi
-		# Handle double hyphen options first
-		if [[ "$item" = '--help' ]]; then
-			mkdir_audit_log "$DAISY_CHAIN \"--help\"\n";
-			$DAISY_CHAIN "--help";
-			exit 0;
-		fi
-		if [[ "$item" = '--version' ]]; then
-			mkdir_audit_log "$DAISY_CHAIN \"--version\"\n";
-			$DAISY_CHAIN "--version";
-			exit 0;
-		fi
-		regex="^--context[=]*(.*)$";
-		if [[ "$item" =~ $regex ]]; then
-		    if [[ -z "${BASH_REMATCH[1]}" ]]; then
-				addnext=1;
-			fi
-			options="$options $item";
-			continue;
-		fi
-		regex="^--mode[=]*(.*)$";
-		if [[ "$item" =~ $regex ]]; then
-			if [[ -z "${BASH_REMATCH[1]}" ]]; then
-				addnext=1;
-			fi
-			options="$options $item";
-			continue;
-		fi
-		regex="^--.+$";# catch other double hyphen options
-		if [[ "$item" =~ $regex ]]; then
-			options="$options $item";
-			continue;
-		fi	
-		# these options can be mashed all together mostly
-		regex="^-([^-]+)$";# single hyphen option(s)
-		if [[ "$item" =~ $regex ]]; then
-			mashed="${BASH_REMATCH[1]}";
-			out_options="-";
-			out_flag=0;
-			olength=${#mashed};
-			# We need to process these options from left to right
-			for (( i=0; i<$olength; i++ )); do
-				ochar=${mashed:$i:1};
-				case "$ochar" in
-					[pv])  out_flag=1;# An option we want to keep
-						out_options="$out_options$ochar";
-						;;					
-					*) 	remainder=$((olength-i));
-						mashed=${mashed:$i:$remainder};# get remaining chars
-						break;
-				esac
-			done
-			# add these captured options if any
-			if [[ $out_flag -eq 1 ]]; then
-				options="$options $out_options";				
-			fi		
-			# The rest of these if I save them at all I want separated out.
-			# These options are special since if they were mashed with other
-			# options they would have to be at the end of the mess to be valid.	
-			regex="^m(.*)$"; # find any mode option
-			if [[ "$mashed" =~ $regex ]]; then
-				if [[ -z "${BASH_REMATCH[1]}" ]]; then
-					addnext=1;
-				fi
-				options="$options -m${BASH_REMATCH[1]}";
-				continue;				
-			fi
-			regex="^Z(.*)$"; # find any SELinux security context
-			if [[ "$mashed" =~ $regex  ]]; then
-				if [[ -z "${BASH_REMATCH[1]}" ]]; then
-					addnext=1;
-				fi
-				options="$options -Z${BASH_REMATCH[1]}";
-				continue;
-			fi
-			continue;
-		fi
-		files+=("$item");
-		add_escaped_file;
-	else
-		files+=("$item");
-		add_escaped_file;
-	fi
+    if [[ $stopgettingoptions -eq 0 ]]; then
+        if [[ "$item" = '--' ]]; then
+            options="$options $item";
+            stopgettingoptions=1;
+            continue;
+        fi
+        # With options, spaces are assumed to delimit the options so we need
+        # continuation logic to process options that have been split with spaces.
+        if [[ $addnext -eq 1 ]];then
+            if [[ "$item" = '=' ]]; then
+                options="$options $item";
+            else
+                addnext=0;
+                options="$options $item";
+            fi
+            continue;
+        fi
+        # Handle double hyphen options first
+        if [[ "$item" = '--help' ]]; then
+            mkdir_audit_log "$DAISY_CHAIN \"--help\"\n";
+            $DAISY_CHAIN "--help";
+            exit 0;
+        fi
+        if [[ "$item" = '--version' ]]; then
+            mkdir_audit_log "$DAISY_CHAIN \"--version\"\n";
+            $DAISY_CHAIN "--version";
+            exit 0;
+        fi
+        regex="^--context[=]*(.*)$";
+        if [[ "$item" =~ $regex ]]; then
+            if [[ -z "${BASH_REMATCH[1]}" ]]; then
+                addnext=1;
+            fi
+            options="$options $item";
+            continue;
+        fi
+        regex="^--mode[=]*(.*)$";
+        if [[ "$item" =~ $regex ]]; then
+            if [[ -z "${BASH_REMATCH[1]}" ]]; then
+                addnext=1;
+            fi
+            options="$options $item";
+            continue;
+        fi
+        regex="^--.+$";# catch other double hyphen options
+        if [[ "$item" =~ $regex ]]; then
+            options="$options $item";
+            continue;
+        fi  
+        # these options can be mashed all together mostly
+        regex="^-([^-]+)$";# single hyphen option(s)
+        if [[ "$item" =~ $regex ]]; then
+            mashed="${BASH_REMATCH[1]}";
+            out_options="-";
+            out_flag=0;
+            olength=${#mashed};
+            # We need to process these options from left to right
+            for (( i=0; i<$olength; i++ )); do
+                ochar=${mashed:$i:1};
+                case "$ochar" in
+                   [mZ]) remainder=$((olength-i));
+                         mashed=${mashed:$i:$remainder};# get remaining chars
+                         break;;
+                      *): # Save everything else, should support future options.
+                         out_flag=1;# An option we want to keep
+                         out_options="$out_options$ochar";
+                         ;;                     
+                esac
+            done
+            # add these captured options if any
+            if [[ $out_flag -eq 1 ]]; then
+                options="$options $out_options";                
+            fi      
+            # The rest of these if I save them at all I want separated out.
+            # These options are special since if they were mashed with other
+            # options they would have to be at the end of the mess to be valid. 
+            regex="^m(.*)$"; # find any mode option
+            if [[ "$mashed" =~ $regex ]]; then
+                if [[ -z "${BASH_REMATCH[1]}" ]]; then
+                    addnext=1;
+                fi
+                options="$options -m${BASH_REMATCH[1]}";
+                continue;               
+            fi
+            regex="^Z(.*)$"; # find any SELinux security context
+            if [[ "$mashed" =~ $regex  ]]; then
+                if [[ -z "${BASH_REMATCH[1]}" ]]; then
+                    addnext=1;
+                fi
+                options="$options -Z${BASH_REMATCH[1]}";
+                continue;
+            fi
+            continue;
+        fi
+        files+=("$item");
+        add_escaped_file;
+    else
+        files+=("$item");
+        add_escaped_file;
+    fi
 done
 
 # At this point we have split options from directories.
@@ -216,16 +234,16 @@ done
 # whole options string.
 
 doclean(){
-	regex=$1;
-	while [[ $options =~ $regex ]];
-	do
-		if [[ $notify -eq 1 ]]; then report=1; fi
-	    if [[ "${BASH_REMATCH[2]}" = "," ]];then
-		   options="${BASH_REMATCH[1]}${BASH_REMATCH[3]}";
-		else
-		   options="${BASH_REMATCH[1]}${BASH_REMATCH[2]}${BASH_REMATCH[3]}";
-		fi
-	done
+    regex=$1;
+    while [[ $options =~ $regex ]];
+    do
+        if [[ $notify -eq 1 ]]; then report=1; fi
+        if [[ "${BASH_REMATCH[2]}" = "," ]];then
+           options="${BASH_REMATCH[1]}${BASH_REMATCH[3]}";
+        else
+           options="${BASH_REMATCH[1]}${BASH_REMATCH[2]}${BASH_REMATCH[3]}";
+        fi
+    done
 }
 notify=0;
 # Keep only the last 4 digits of the OCTAL-MODE.
@@ -245,15 +263,15 @@ options="$options ";# we need a trailing space for the clean up to work
 # Because the characters "ugo" can occur on either side of the "="
 regex="(.*\s)(--mode|-m)\s*=*\s*\S*[\+=-][rwxXtugo]+\S*\s(.*)";
 if [[ $options =~ $regex ]]; then
-	:
-	# We probably want to keep some of this.
+    :
+    # We probably want to keep some of this.
 else
-	# eliminate any symbolic --mode setting that would be empty if we removed "s"
-	regex="(.*\s)--mode\s*=*\s*[^rwxXt[:space:]0-7]+\s(.*)";
-	doclean $regex;
-	# eliminate any symbolic -m setting that would be empty if we removed "s"
-	regex="(.*\s)-m\s*[^rwxXt[:space:]0-7]+\s(.*)";
-	doclean $regex;
+    # eliminate any symbolic --mode setting that would be empty if we removed "s"
+    regex="(.*\s)--mode\s*=*\s*[^rwxXt[:space:]0-7]+\s(.*)";
+    doclean $regex;
+    # eliminate any symbolic -m setting that would be empty if we removed "s"
+    regex="(.*\s)-m\s*[^rwxXt[:space:]0-7]+\s(.*)";
+    doclean $regex;
 fi
 notify=1;
 # eliminate any "s" option in the symbolic --mode parameters
@@ -286,24 +304,50 @@ doclean $regex;
 
 if [[ $report -eq 1 ]]; then report_filtered; fi
 
+# An interesting issue arose when installing tcl8.6.0. The package is setting
+# a very restrictive umask for copy operations which resulted in the wrapper
+# creating read only temporary files, which caused the wrapper to fail.
+save_umask=$(umask);# backup the current umask
+umask 0077; # set a usable umask
 error_file=$(mktemp -t mkdir.XXXXXXXXXX);# temporary file for stderr output
+umask "$save_umask";# restore backed up umask
+
 for directory in "${files[@]}"; do
-	error_code=0;
-	audit_text="";
-	if [[ -e "$directory" ]]; then
-		:
-		# We avoid most ownership issues by skipping existing directories
-		# echo "*** Directory already exists: \"$directory\""
-	else
-		$DAISY_CHAIN $options "$directory" 2>"$error_file" || error_code="$?";
-		ERROR=$(<"$error_file");
-		if [[ "$error_code" -ne 0 ]]; then
-			audit_text="ERROR: $ERROR";
-			echo "$ERROR" 1>&2; # output to stdout and stderr
-			pass_error="$error_code";
-		fi
-		mkdir_audit_log "$DAISY_CHAIN$options $(echo \"$directory\" | sed -e 's/%/%%/g')\n";
-	fi
+    error_code=0;
+    audit_text="";
+    if [[ -e "$directory" ]]; then
+        :
+        if [ -z ${DISABLE_WRAPPER_WARNINGS+x} ]; then
+            # DISABLE_WRAPPER_WARNINGS is unset
+            # default behavior of mkdir is to not issue a warning for already
+            # existing directories if the -p option is given
+            DISABLE_WRAPPER_WARNINGS=1;
+            existing_dir_error_code=1;# mkdir does return an error code of 1 for
+            # already existing directories even if the -p option is given
+        fi
+        if [[ "$DISABLE_WRAPPER_WARNINGS" -eq 0 ]]; then            
+            echo 1>&2 "*** The directory or file \"$directory\" already exists. Skipping...";
+            echo 1>&2 "*** See the \"$HOME/mkdir_syntax_errors.txt\" file for details";
+            error_text="The directory or file $(echo \"$directory\" | sed  -e 's/%/%%/g') already exists. Skipping...\n";
+            report_errors "$error_text";
+        fi
+        if [[ "$DISABLE_WRAPPER_ERROR_CODES" -eq 0 ]]; then
+            existing_dir_error_code=1;
+        fi      
+    else
+        $DAISY_CHAIN $options "$directory" 2>"$error_file" || error_code="$?";
+        ERROR=$(<"$error_file");
+        if [[ "$error_code" -ne 0 ]]; then
+            audit_text="ERROR: $ERROR";
+            echo "$ERROR" 1>&2; # output to stdout and stderr
+            pass_error="$error_code";
+        fi
+        mkdir_audit_log "$DAISY_CHAIN$options $(echo \"$directory\" | sed -e 's/%/%%/g')\n";
+    fi
 done
 $UNLINK_BYPASS "$error_file"; # remove temporary file
+# Carry forward error codes from any existing directory issues
+if [[ $existing_dir_error_code -eq 1 ]]; then
+    pass_error="$existing_dir_error_code";
+fi
 exit "$pass_error";
diff --git a/lib/rm b/lib/rm
--- a/lib/rm
+++ b/lib/rm
@@ -7,17 +7,17 @@ DAISY_CHAIN="";
 me=$(whoami);
 reportmsg="rm";
 for item in "$@"; do
-	regex="^.*['[:space:]].*$";
-	if [[ "$item" =~ $regex ]]; then
-	    regex="^(.*=)(.*['[:space:]].*)$";
-	    if [[ "$item" =~ $regex ]]; then
-			reportmsg="$reportmsg ${BASH_REMATCH[1]}\"${BASH_REMATCH[2]}\"";
-		else
-			reportmsg="$reportmsg \"$item\"";
-		fi
-	else
-		reportmsg="$reportmsg $item";
-	fi
+    regex="^.*['[:space:]].*$";
+    if [[ "$item" =~ $regex ]]; then
+        regex="^(.*=)(.*['[:space:]].*)$";
+        if [[ "$item" =~ $regex ]]; then
+            reportmsg="$reportmsg ${BASH_REMATCH[1]}\"${BASH_REMATCH[2]}\"";
+        else
+            reportmsg="$reportmsg \"$item\"";
+        fi
+    else
+        reportmsg="$reportmsg $item";
+    fi
 done
 
 for p in $(type -ap rm) ; do
@@ -29,8 +29,15 @@ if [ -z "$DAISY_CHAIN" ]; then
   exit 1;
 fi
 
-if [ $UID -eq 0 ]; then
-  $DAISY_CHAIN "$@";
+error_code=0;
+if [[ $UID -eq 0 ]]; then
+  $DAISY_CHAIN "$@" || error_code="$?";
+  exit $error_code; #pass back any error code
+fi
+
+if [[ "$DISABLE_WRAPPERS" -eq 1 ]]; then
+  $DAISY_CHAIN "$@" || error_code="$?";
+  exit $error_code; #pass back any error code
 fi
 
 # "options" and "files" are arrays. In the case of files this helped preserve
@@ -45,170 +52,243 @@ pwd=$(pwd);
 item="";
 audit_text="";
 error_code=0;
+error_code_for_missing=0;
 f_seen=0;
 
 report_owner_issues(){
-	text="\n";
-	text="$text ------file ownership issues-------------\n";
-	text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
-	text="$text $(echo $reportmsg | sed -e 's/%/%%/g')\n";
-	text="$text $1\n";
-	printf "$text" >>"$HOME/rm_owner_issues.txt";
+    text="\n";
+    text="$text ------file ownership issues-------------\n";
+    text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
+    text="$text $(echo $reportmsg | sed -e 's/%/%%/g')\n";
+    text="$text $1\n";
+    printf "$text" >>"$HOME/rm_owner_issues.txt";
+}
+report_errors(){
+    text="\n";
+    text="$text ------rm command syntax errors-------------\n";
+    text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
+    text="$text $(echo $reportmsg | sed  -e 's/%/%%/g')\n";
+    text="$text $1\n";
+    printf "$text" >>"$HOME/rm_syntax_errors.txt";
 }
 rm_audit_log(){
-	text="\n";
-	text="$text ------ original command -------------\n";
-	text="$text $(echo $reportmsg | sed -e 's/%/%%/g')\n";
-	text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
-	text="$text ------ The resulting command actually run -------\n";
-	text="$text $1";
-	if [[ -n "$audit_text" ]]; then
-		text="$text error_code is: $error_code\n";
-		text="$text $(echo $audit_text | sed -e 's/%/%%/g')\n";
-		printf "$text" >>"$HOME/rm_errors.txt"
-	fi
-	# while debugging this wrapper you may wish to uncomment the following line
-	#printf "$text" >>"$HOME/rm_audit.txt";
+    text="\n";
+    text="$text ------ original command -------------\n";
+    text="$text $(echo $reportmsg | sed -e 's/%/%%/g')\n";
+    text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
+    text="$text ------ The resulting command actually run -------\n";
+    text="$text $1";
+    if [[ -n "$audit_text" ]]; then
+        text="$text error_code is: $error_code\n";
+        text="$text $(echo $audit_text | sed -e 's/%/%%/g')\n";
+        printf "$text" >>"$HOME/rm_errors.txt"
+    fi
+    if [[ "$ENABLE_WRAPPER_AUDIT" -eq 1 ]]; then
+        # log all rm commands actually run
+        printf "$text" >>"$HOME/rm_audit.txt";
+    fi
 }
 
 # Syntax
 # rm [OPTION]... FILE...
 
 process_file(){
-	if [[ -e "$item" ]] || [[ -h "$item" ]]; then
-			# Exists as a directory, file or link so check ownership
-			if [[ -d "$item" ]]; then
-				# To be thorough, if we are talking about removing a directory
-				# we should report ownership issues for any of the contained
-				# files or directories as well.
-				while IFS="" read -r -d "" file ; do
-					find_array+=("$file");
-				done < <(find "$item" -print0)
-				for found_item in "${find_array[@]}"; do
-					owner=$(stat -c%U -- "$found_item");
-					if [[ -d "$found_item" ]]; then
-						object="directory";
-					else
-						object="file or link";
-					fi
-					if [[ "$owner" != "$me" ]]; then
-						owner_issues=1;
-						echo 1>&2 "*** The $object: \"$found_item\"  is owned by \"$owner\" and not \"$me\"";
-						echo 1>&2 "*** See the \"$HOME/rm_owner_issues.txt\" file for details";
-						error_text="The $object: $(echo \"$found_item\" | sed -e 's/%/%%/g') is owned by \"$owner\" and not \"$me\"\n";
-						error_text="$error_text In order to remove the directory $(echo \"$item\" | sed -e 's/%/%%/g')\n";
-						error_text="$error_text this ownership issue needs to be corrected.\n";
-						report_owner_issues "$error_text";
-						regex2="^[^/].*$"; # should only match if it is not a real full path
-						if [[ "$found_item" =~ $regex2 ]]; then
-							echo "$pwd/$found_item">>"$HOME/rm_owner_file_list.txt";
-						else
-							echo "$found_item">>"$HOME/rm_owner_file_list.txt";
-						fi
-					fi
-				done
-			else
-				owner=$(stat -c%U -- "$item");
-				object="file or link";
-				if [[ "$owner" != "$me" ]]; then
-				    owner_issues=1;
-					echo 1>&2 "*** The $object: \"$item\"  is owned by \"$owner\" and not \"$me\"";
-					echo 1>&2 "*** See the \"$HOME/rm_owner_issues.txt\" file for details";
-					error_text="The $object: $(echo \"$item\" | sed -e 's/%/%%/g') is owned by \"$owner\" and not \"$me\"\n";
-					report_owner_issues "$error_text";
-					regex2="^[^/].*$"; # should only match if it is not a real full path
-					if [[ "$item" =~ $regex2 ]]; then
-						echo "$pwd/$item">>"$HOME/rm_owner_file_list.txt";
-					else
-						echo "$item">>"$HOME/rm_owner_file_list.txt";
-					fi
-				fi
-			fi
-			if [[ $owner_issues -eq 0 ]]; then
-				files+=("$item");
-				escaped_item=$(echo "$item" | sed -e 's/\\/\\\\/g' -e 's/"/\\\\"/g');
-				regex="^.*['[:space:]].*$";
-				if [[ "$escaped_item" =~ $regex ]]; then
-					if [[ -z "$escaped_files" ]]; then
-						escaped_files="\"$escaped_item\"";
-					else
-						escaped_files="$escaped_files \"$escaped_item\"";
-					fi
-				else
-					if [[ -z "$escaped_files" ]]; then
-						escaped_files="$escaped_item";
-					else
-						escaped_files="$escaped_files $escaped_item";
-					fi
-				fi
-			fi
-	else
-		:
-		# If the item does not exist as a directory, file or link drop it
-		# and process the next item if any.
-		#echo 1>&2 "*** WARNING: can not remove \"$item\" since it does not exist";
-	fi
+    if [[ -e "$item" ]] || [[ -h "$item" ]]; then
+            # Exists as a directory, file or link so check ownership
+            if [[ -d "$item" ]]; then
+                # To be thorough, if we are talking about removing a directory
+                # we should report ownership issues for any of the contained
+                # files or directories as well.
+                while IFS="" read -r -d "" file ; do
+                    find_array+=("$file");
+                done < <(find "$item" -print0)
+                for found_item in "${find_array[@]}"; do
+                    owner=$(stat -c%U -- "$found_item");
+                    if [[ -d "$found_item" ]]; then
+                        object="directory";
+                    else
+                        object="file or link";
+                    fi
+                    if [[ "$owner" != "$me" ]]; then
+                        owner_issues=1;
+                        echo 1>&2 "*** The $object: \"$found_item\"  is owned by \"$owner\" and not \"$me\"";
+                        echo 1>&2 "*** See the \"$HOME/rm_owner_issues.txt\" file for details";
+                        error_text="The $object: $(echo \"$found_item\" | sed -e 's/%/%%/g') is owned by \"$owner\" and not \"$me\"\n";
+                        error_text="$error_text In order to remove the directory $(echo \"$item\" | sed -e 's/%/%%/g')\n";
+                        error_text="$error_text this ownership issue needs to be corrected.\n";
+                        report_owner_issues "$error_text";
+                        regex2="^[^/].*$"; # should only match if it is not a real full path
+                        if [[ "$found_item" =~ $regex2 ]]; then
+                            echo "$pwd/$found_item">>"$HOME/rm_owner_file_list.txt";
+                        else
+                            echo "$found_item">>"$HOME/rm_owner_file_list.txt";
+                        fi
+                    fi
+                done
+            else
+                owner=$(stat -c%U -- "$item");
+                object="file or link";
+                if [[ "$owner" != "$me" ]]; then
+                    owner_issues=1;
+                    echo 1>&2 "*** The $object: \"$item\"  is owned by \"$owner\" and not \"$me\"";
+                    echo 1>&2 "*** See the \"$HOME/rm_owner_issues.txt\" file for details";
+                    error_text="The $object: $(echo \"$item\" | sed -e 's/%/%%/g') is owned by \"$owner\" and not \"$me\"\n";
+                    report_owner_issues "$error_text";
+                    regex2="^[^/].*$"; # should only match if it is not a real full path
+                    if [[ "$item" =~ $regex2 ]]; then
+                        echo "$pwd/$item">>"$HOME/rm_owner_file_list.txt";
+                    else
+                        echo "$item">>"$HOME/rm_owner_file_list.txt";
+                    fi
+                fi
+            fi
+            if [[ $owner_issues -eq 0 ]]; then
+                files+=("$item");
+                escaped_item=$(echo "$item" | sed -e 's/\\/\\\\/g' -e 's/"/\\\\"/g');
+                regex="^.*['[:space:]].*$";
+                if [[ "$escaped_item" =~ $regex ]]; then
+                    if [[ -z "$escaped_files" ]]; then
+                        escaped_files="\"$escaped_item\"";
+                    else
+                        escaped_files="$escaped_files \"$escaped_item\"";
+                    fi
+                else
+                    if [[ -z "$escaped_files" ]]; then
+                        escaped_files="$escaped_item";
+                    else
+                        escaped_files="$escaped_files $escaped_item";
+                    fi
+                fi
+            fi
+    else
+        :
+        # We get in here if the file, directory or link does not exist.
+        # Note that we are always forcing the -f option to avoid the command
+        # going interactive, interactive mode does not work so well with a 
+        # wrapper script.   
+        if [ -z ${DISABLE_WRAPPER_WARNINGS+x} ]; then
+            # DISABLE_WRAPPER_WARNINGS is unset
+            # default behavior of rm is not to issue a text warning for missing 
+            # files if the -f parameter is issued 
+            DISABLE_WRAPPER_WARNINGS=1;
+            error_code_for_missing=1;# the default rm command does return an error 
+            # code of 1 for missing items even if the -f parameter is given
+        fi
+        if [[ "$DISABLE_WRAPPER_WARNINGS" -eq 0 ]]; then
+            echo 1>&2 "*** The \"rm\" command can not remove \"$item\" since it does not exist";
+            echo 1>&2 "*** See the \"$HOME/rm_syntax_errors.txt\" file for details";
+            error_text="The \"rm\" command can not remove $(echo \"$item\" | sed  -e 's/%/%%/g') since it does not exist\n";
+            report_errors "$error_text";
+        fi
+        if [[ "$DISABLE_WRAPPER_ERROR_CODES" -eq 0 ]]; then
+            error_code_for_missing=1;
+        fi
+    fi
 }
 # This "for" loop manages to process filenames or paths with white space or
 # special characters.
 for item in "$@"; do
-	if [[ $stopgettingoptions -eq 0 ]]; then
-		if [[ "$item" = '--' ]]; then
-			options+=("$item");
-			stopgettingoptions=1;
-			continue;
-		fi
-		if [[ "$item" = '--help' ]]; then
-			rm_audit_log "$DAISY_CHAIN \"--help\"\n";
-			$DAISY_CHAIN "--help";
-			exit 0;
-		fi
-		if [[ "$item" = '--version' ]]; then
-			rm_audit_log "$DAISY_CHAIN \"--version\"\n";
-			$DAISY_CHAIN "--version";
-			exit 0;
-		fi	
-		regex="^-(\S+)$";# There should never be "space" in the rm options.
-		if [[ "$item" =~ $regex ]]; then
-			parsed_option="${BASH_REMATCH[1]}";
-			regex="^.*f.*$"; # contains f
-			if [[ "$parsed_option" =~ $regex ]]; then
-				f_seen=1;
-			fi
-			options+=("$item");
-			continue;
-		fi
-		process_file;
-	else
-		process_file;
-	fi
+    if [[ $stopgettingoptions -eq 0 ]]; then
+        if [[ "$item" = '--' ]]; then
+            options+=("$item");
+            stopgettingoptions=1;
+            continue;
+        fi
+        # With options, spaces are assumed to delimit the options so we need
+        # continuation logic to process options that have been split with spaces.
+        if [[ $remnext -eq 1 ]]; then
+            if [[ "$item" != '=' ]]; then
+                remnext=0;
+            fi
+            continue;
+        fi
+        if [[ "$item" = '--help' ]]; then
+            rm_audit_log "$DAISY_CHAIN \"--help\"\n";
+            $DAISY_CHAIN "--help";
+            exit 0;
+        fi
+        if [[ "$item" = '--version' ]]; then
+            rm_audit_log "$DAISY_CHAIN \"--version\"\n";
+            $DAISY_CHAIN "--version";
+            exit 0;
+        fi  
+        if [[ "$item" = '--interactive' ]]; then
+            continue;
+        fi  
+        regex="^--interactive=(.*)$";
+        if [[ "$item" =~ $regex ]]; then
+            if [[ -z "${BASH_REMATCH[1]}" ]]; then
+                remnext=1;
+            fi
+            continue;
+        fi
+        if [[ "$item" = '--force' ]]; then
+            f_seen=1;
+        fi
+        regex="^--.+$";# catch other double hyphen options
+        if [[ "$item" =~ $regex ]]; then
+            options+=("$item");
+            continue;
+        fi
+        regex="^-(\S+)$";# By this point there could only be single - options
+        if [[ "$item" =~ $regex ]]; then
+            parsed_option="${BASH_REMATCH[1]}";
+            regex="^.*f.*$"; # contains f
+            if [[ "$parsed_option" =~ $regex ]]; then
+                f_seen=1;
+            fi
+            # Clean the letter i from the options
+            regex="^(-.*)[iI](.*)$";
+            while [[ "$item" =~ $regex ]];
+            do
+                item="${BASH_REMATCH[1]}${BASH_REMATCH[2]}";
+            done
+            # No sense adding an empty option
+            if [[ "$item" != "-" ]]; then
+                options+=("$item");
+            fi
+            continue;
+        fi
+        process_file;
+    else
+        process_file;
+    fi
 done
 
 # If you decide not to force the -f option and comment out this switch addition,
 # then if the rm command run would require user interaction, it will appear as 
 # though this wrapper script has locked up.
 if [[ "$f_seen" -eq 0 ]]; then
-	options+=("-f");
+    options+=("-f");
 fi
 
 if [[ -n "${files[@]}" ]];then
-	error_file=$(mktemp -t rm.XXXXXXXXXX);# temporary file for stderr output
-	escaped_files="$(echo $escaped_files | sed -e 's/%/%%/g')";
-	set --; #clear passed arguments
-	set -- "${options[@]}" "${files[@]}"; #set new ones
-	$DAISY_CHAIN "$@" 2>"$error_file" || error_code="$?";
-	ERROR=$(<"$error_file");	
-	if [[ "$error_code" -ne 0 ]]; then
-		audit_text="ERROR: $ERROR";
-		echo "$ERROR" 1>&2; # output to stdout and stderr
-	fi
-	if [[ -n "${options[@]}" ]]; then
-		options="${options[@]}";# something odd with LFS required this step
-		rm_audit_log "$DAISY_CHAIN $options $escaped_files\n";
-	else
-		rm_audit_log "$DAISY_CHAIN $escaped_files\n";
-	fi
-	$DAISY_CHAIN "$error_file";# remove temporary file
+    # An interesting issue arose when installing tcl8.6.0. The package is setting
+    # a very restrictive umask for copy operations which resulted in the wrapper
+    # creating read only temporary files, which caused the wrapper to fail.
+    save_umask=$(umask);# backup the current umask
+    umask 0077; # set a usable umask
+    error_file=$(mktemp -t rm.XXXXXXXXXX);# temporary file for stderr output
+    umask "$save_umask";# restore backed up umask
+    escaped_files="$(echo $escaped_files | sed -e 's/%/%%/g')";
+    set --; #clear passed arguments
+    set -- "${options[@]}" "${files[@]}"; #set new ones
+    $DAISY_CHAIN "$@" 2>"$error_file" || error_code="$?";
+    ERROR=$(<"$error_file");    
+    if [[ "$error_code" -ne 0 ]]; then
+        audit_text="ERROR: $ERROR";
+        echo "$ERROR" 1>&2; # output to stdout and stderr
+    fi
+    if [[ -n "${options[@]}" ]]; then
+        options="${options[@]}";# something odd with LFS required this step
+        rm_audit_log "$DAISY_CHAIN $options $escaped_files\n";
+    else
+        rm_audit_log "$DAISY_CHAIN $escaped_files\n";
+    fi
+    $DAISY_CHAIN "$error_file";# remove temporary file
 fi
-
+# Carry forward error codes from any missing items
+if [[ $error_code_for_missing -eq 1 ]]; then
+    error_code="$error_code_for_missing";
+fi
 exit $error_code;
diff --git a/lib/sln b/lib/sln
--- a/lib/sln
+++ b/lib/sln
@@ -8,17 +8,17 @@ UNLINK_BYPASS="";
 me=$(whoami);
 reportmsg="sln";
 for item in "$@"; do
-	regex="^.*['[:space:]].*$";
-	if [[ "$item" =~ $regex ]]; then
-	    regex="^(.*=)(.*['[:space:]].*)$";
-	    if [[ "$item" =~ $regex ]]; then
-			reportmsg="$reportmsg ${BASH_REMATCH[1]}\"${BASH_REMATCH[2]}\"";
-		else
-			reportmsg="$reportmsg \"$item\"";
-		fi
-	else
-		reportmsg="$reportmsg $item";
-	fi
+    regex="^.*['[:space:]].*$";
+    if [[ "$item" =~ $regex ]]; then
+        regex="^(.*=)(.*['[:space:]].*)$";
+        if [[ "$item" =~ $regex ]]; then
+            reportmsg="$reportmsg ${BASH_REMATCH[1]}\"${BASH_REMATCH[2]}\"";
+        else
+            reportmsg="$reportmsg \"$item\"";
+        fi
+    else
+        reportmsg="$reportmsg $item";
+    fi
 done
 
 for p in $(type -ap sln) ; do
@@ -30,8 +30,15 @@ if [ -z "$DAISY_CHAIN" ]; then
   exit 1;
 fi
 
-if [ $UID -eq 0 ]; then
-  $DAISY_CHAIN "$@";
+error_code=0;
+if [[ $UID -eq 0 ]]; then
+  $DAISY_CHAIN "$@" || error_code="$?";
+  exit $error_code; #pass back any error code
+fi
+
+if [[ "$DISABLE_WRAPPERS" -eq 1 ]]; then
+  $DAISY_CHAIN "$@" || error_code="$?";
+  exit $error_code; #pass back any error code
 fi
 
 for p in $(type -ap unlink) ; do
@@ -46,40 +53,49 @@ files=();
 owner="";
 pass_error=0;
 pwd=$(pwd);
-error_file=$(mktemp -t sln.XXXXXXXXXX);# temporary file for stderr output
 error_code=0;
 audit_text="";
+
+# An interesting issue arose when installing tcl8.6.0. The package is setting
+# a very restrictive umask for copy operations which resulted in the wrapper
+# creating read only temporary files, which caused the wrapper to fail.
+save_umask=$(umask);# backup the current umask
+umask 0077; # set a usable umask
+error_file=$(mktemp -t sln.XXXXXXXXXX);# temporary file for stderr output
+umask "$save_umask";# restore backed up umask
 
 # Because of multi-threading.. multiple line entries need to be done as one
 # one write to the log file.
 report_errors(){
-	text="\n";
-	text="$text ------sln command syntax errors-------------\n";
-	text="$text $(echo $reportmsg | sed -e 's/%/%%/g')\n";
-	text="$text $1\n";
-	printf "$text" >>"$HOME/sln_syntax_errors.txt";
+    text="\n";
+    text="$text ------sln command syntax errors-------------\n";
+    text="$text $(echo $reportmsg | sed -e 's/%/%%/g')\n";
+    text="$text $1\n";
+    printf "$text" >>"$HOME/sln_syntax_errors.txt";
 }
 report_owner_issues(){
-	text="\n";
-	text="$text ------link ownership issues-------------\n";
-	text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
-	text="$text $1\n";
-	printf "$text" >>"$HOME/sln_owner_issues.txt";
+    text="\n";
+    text="$text ------link ownership issues-------------\n";
+    text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
+    text="$text $1\n";
+    printf "$text" >>"$HOME/sln_owner_issues.txt";
 }
 sln_audit_log(){
-	text="\n";
-	text="$text ------ original command -------------\n";
-	text="$text $(echo $reportmsg | sed -e 's/%/%%/g')\n";
-	text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
-	text="$text ------ one of the resulting commands actually run -------\n";
-	text="$text $1";
-	if [[ -n "$audit_text" ]]; then
-		text="$text error_code is: $error_code\n";
-		text="$text $(echo $audit_text | sed -e 's/%/%%/g')\n";
-		printf "$text" >>"$HOME/sln_errors.txt";
-	fi
-	# while debugging the wrapper you may wish to uncomment the following line
-	#printf "$text" >>"$HOME/sln_audit.txt";
+    text="\n";
+    text="$text ------ original command -------------\n";
+    text="$text $(echo $reportmsg | sed -e 's/%/%%/g')\n";
+    text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
+    text="$text ------ one of the resulting commands actually run -------\n";
+    text="$text $1";
+    if [[ -n "$audit_text" ]]; then
+        text="$text error_code is: $error_code\n";
+        text="$text $(echo $audit_text | sed -e 's/%/%%/g')\n";
+        printf "$text" >>"$HOME/sln_errors.txt";
+    fi
+    if [[ "$ENABLE_WRAPPER_AUDIT" -eq 1 ]]; then
+        # log all sln commands actually run
+        printf "$text" >>"$HOME/sln_audit.txt";
+    fi
 }
 
 # Syntax
@@ -92,95 +108,98 @@ sln_audit_log(){
 #
 
 do_sln(){
-	error_code=0;
-	audit_text="";
-	regex="(.*)/([^/]+)$";
-	if [[ "$option2" =~ $regex ]]; then
-		if [[ -n "${BASH_REMATCH[1]}" ]]; then
-			linkpath=$(readlink -f -- "${BASH_REMATCH[1]}");
-		else
-			linkpath="";
-		fi
-		linkname="${BASH_REMATCH[2]}";
-	else
-		linkpath="$pwd";
-		linkname="$option2";
-	fi
-	fulllinkname="$linkpath/$linkname";
-	if [[ -e "$option2" ]] || [[ -h "$option2" ]]; then
-		owner=$(stat -c%U -- "$fulllinkname");
-		if [[ "$owner" != "$me" ]]; then
-		    echo 1>&2 "*** The file: \"$fulllinkname\" is owned by \"$owner\" and not \"$me\"";
-			echo 1>&2 "*** See the \"$HOME/sln_owner_issues.txt\" file for details";
-			error_text="The file: $(echo \"$fulllinkname\" | sed -e 's/%/%%/g') is owned by \"$owner\" and not \"$me\"\n";
-			error_text="$error_text$DAISY_CHAIN $(echo \"$option1\" | sed -e 's/%/%%/g') $(echo \"$option2\" | sed -e 's/%/%%/g')\n";
-			report_owner_issues "$error_text";
-			echo "$fulllinkname">>"$HOME/sln_owner_file_list.txt";
-			return;
-		fi
-	fi
-	if [[ -e "$option1" ]] || [[ -h "$option1" ]]; then		
-		$DAISY_CHAIN "$option1" "$option2" 2>"$error_file" || error_code="$?";
-		ERROR=$(<"$error_file");		
-		if [[ "$error_code" -ne 0 ]]; then
-			audit_text="ERROR: $ERROR";
-			echo "$ERROR" 1>&2; # output to stdout and stderr
-			pass_error="$error_code";
-		fi
-		sln_audit_log "$DAISY_CHAIN $(echo \"$option1\" | sed -e 's/%/%%/g') $(echo \"$option2\" | sed -e 's/%/%%/g')\n";
-	else
-		:
-		# The TARGET file or directory is missing.
-	fi
+    error_code=0;
+    audit_text="";
+    regex="(.*)/([^/]+)$";
+    if [[ "$option2" =~ $regex ]]; then
+        if [[ -n "${BASH_REMATCH[1]}" ]]; then
+            linkpath=$(readlink -f -- "${BASH_REMATCH[1]}");
+        else
+            linkpath="";
+        fi
+        linkname="${BASH_REMATCH[2]}";
+    else
+        linkpath="$pwd";
+        linkname="$option2";
+    fi
+    fulllinkname="$linkpath/$linkname";
+    if [[ -e "$option2" ]] || [[ -h "$option2" ]]; then
+        owner=$(stat -c%U -- "$fulllinkname");
+        if [[ "$owner" != "$me" ]]; then
+            echo 1>&2 "*** The file: \"$fulllinkname\" is owned by \"$owner\" and not \"$me\"";
+            echo 1>&2 "*** See the \"$HOME/sln_owner_issues.txt\" file for details";
+            error_text="The file: $(echo \"$fulllinkname\" | sed -e 's/%/%%/g') is owned by \"$owner\" and not \"$me\"\n";
+            error_text="$error_text$DAISY_CHAIN $(echo \"$option1\" | sed -e 's/%/%%/g') $(echo \"$option2\" | sed -e 's/%/%%/g')\n";
+            report_owner_issues "$error_text";
+            echo "$fulllinkname">>"$HOME/sln_owner_file_list.txt";
+            return;
+        fi
+    fi
+    if [[ -e "$option1" ]] || [[ -h "$option1" ]]; then     
+        $DAISY_CHAIN "$option1" "$option2" 2>"$error_file" || error_code="$?";
+        ERROR=$(<"$error_file");        
+        if [[ "$error_code" -ne 0 ]]; then
+            audit_text="ERROR: $ERROR";
+            echo "$ERROR" 1>&2; # output to stdout and stderr
+            pass_error="$error_code";
+        fi
+        sln_audit_log "$DAISY_CHAIN $(echo \"$option1\" | sed -e 's/%/%%/g') $(echo \"$option2\" | sed -e 's/%/%%/g')\n";
+    else
+        :
+        # The TARGET file or directory is missing.
+    fi
 }
 
 option1="$1";
 option2="$2";
 
 if [[ -n "$option2" ]]; then
-	do_sln;
+    do_sln;
 else
-	if [[ -e "$option1" ]]; then
-		# Special characters and spaces for parameters listed in the file
-		# should be quoted or escaped just like they would need to be on the
-		# command line. We need to escape the backslash to avoid losing it
-		# early in our processing.
-		filename=$(mktemp -t file.XXXXXXXXXX);# temporary file for sln options
-		sed -e 's/\\/\\\\/g' "$option1" > "$filename";
-		while read LINE; do
-			option1="";
-			option2="";
-		    files=();
-		    eval files+=("$LINE");
-			option1="${files[0]}";
-			option2="${files[1]}";
-			if [[ -n "$option2" ]]; then
-				do_sln;
-			fi
-		done < "$filename"
-		# if there was no linefeed on the last line...
-		if [[ -n "$LINE" ]] ; then
-			option1="";
-			option2="";
-		    files=();
-		    eval files+=("$LINE");
-			option1="${files[0]}";
-			option2="${files[1]}";
-			if [[ -n "$option2" ]]; then
-				do_sln;
-			fi
-		fi
-		$UNLINK_BYPASS "$filename";
-	else
-		echo 1>&2 "*** ERROR: With only one parameter, sln expects this to refer";
-		echo 1>&2 "*** to a file that contains a list of parameters.";
-		echo 1>&2 "*** See the \"$HOME/sln_syntax_errors.txt\" file for details";
-		error_text="ERROR: With only one parameter, sln expects this to refer\n";
-		error_text="$error_text to a file that contains a list of parameters.\n";
-		report_errors "$error_text\n";
-		$UNLINK_BYPASS "$error_file"; # remove temporary file
-		exit 1;
-	fi
+    if [[ -e "$option1" ]]; then
+        save_umask=$(umask);# backup the current umask
+        umask 0077; # set a usable umask
+        filename=$(mktemp -t file.XXXXXXXXXX);# temporary file for sln options
+        umask "$save_umask";# restore backed up umask
+        # Special characters and spaces for parameters listed in the file
+        # should be quoted or escaped just like they would need to be on the
+        # command line. We need to escape the backslash to avoid losing it
+        # early in our processing.      
+        sed -e 's/\\/\\\\/g' "$option1" > "$filename";
+        while read LINE; do
+            option1="";
+            option2="";
+            files=();
+            eval files+=("$LINE");
+            option1="${files[0]}";
+            option2="${files[1]}";
+            if [[ -n "$option2" ]]; then
+                do_sln;
+            fi
+        done < "$filename"
+        # if there was no linefeed on the last line...
+        if [[ -n "$LINE" ]] ; then
+            option1="";
+            option2="";
+            files=();
+            eval files+=("$LINE");
+            option1="${files[0]}";
+            option2="${files[1]}";
+            if [[ -n "$option2" ]]; then
+                do_sln;
+            fi
+        fi
+        $UNLINK_BYPASS "$filename";
+    else
+        echo 1>&2 "*** ERROR: With only one parameter, sln expects this to refer";
+        echo 1>&2 "*** to a file that contains a list of parameters.";
+        echo 1>&2 "*** See the \"$HOME/sln_syntax_errors.txt\" file for details";
+        error_text="ERROR: With only one parameter, sln expects this to refer\n";
+        error_text="$error_text to a file that contains a list of parameters.\n";
+        report_errors "$error_text\n";
+        $UNLINK_BYPASS "$error_file"; # remove temporary file
+        exit 1;
+    fi
 fi
 $UNLINK_BYPASS "$error_file"; # remove temporary file
 exit "$pass_error";
diff --git a/lib/tar b/lib/tar
--- a/lib/tar
+++ b/lib/tar
@@ -8,17 +8,17 @@ UNLINK_BYPASS="";
 me=$(whoami);
 reportmsg="tar";
 for item in "$@"; do
-	regex="^.*['[:space:]].*$";
-	if [[ "$item" =~ $regex ]]; then
-	    regex="^(.*=)(.*['[:space:]].*)$";
-	    if [[ "$item" =~ $regex ]]; then
-			reportmsg="$reportmsg ${BASH_REMATCH[1]}\"${BASH_REMATCH[2]}\"";
-		else
-			reportmsg="$reportmsg \"$item\"";
-		fi
-	else
-		reportmsg="$reportmsg $item";
-	fi
+    regex="^.*['[:space:]].*$";
+    if [[ "$item" =~ $regex ]]; then
+        regex="^(.*=)(.*['[:space:]].*)$";
+        if [[ "$item" =~ $regex ]]; then
+            reportmsg="$reportmsg ${BASH_REMATCH[1]}\"${BASH_REMATCH[2]}\"";
+        else
+            reportmsg="$reportmsg \"$item\"";
+        fi
+    else
+        reportmsg="$reportmsg $item";
+    fi
 done
 
 for p in $(type -ap tar) ; do
@@ -30,8 +30,15 @@ if [ -z "$DAISY_CHAIN" ]; then
   exit 1;
 fi
 
-if [ $UID -eq 0 ]; then
-  $DAISY_CHAIN "$@";
+error_code=0;
+if [[ $UID -eq 0 ]]; then
+  $DAISY_CHAIN "$@" || error_code="$?";
+  exit $error_code; #pass back any error code
+fi
+
+if [[ "$DISABLE_WRAPPERS" -eq 1 ]]; then
+  $DAISY_CHAIN "$@" || error_code="$?";
+  exit $error_code; #pass back any error code
 fi
 
 for p in $(type -ap unlink) ; do
@@ -58,31 +65,41 @@ owner=$(stat -c%U -- "$pwd");
 # It might be nice to know where "tar" is run, what parameters it is given
 # and who owns the directory that "tar" is being run in.
 report_tar_useage(){
-	text="\n";
-	text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
-	text="$text owner of $(echo \"$pwd\" | sed -e 's/%/%%/g') is: \"$owner\"\n";
-	text="$text $(echo $reportmsg | sed -e 's/%/%%/g')\n";
-	if [[ -n "$audit_text" ]]; then
-		text="$text error_code is: $error_code\n";
-		text="$text $(echo $audit_text | sed -e 's/%/%%/g')\n";
-		printf "$text" >>"$HOME/tar_errors.txt";
-	fi
-	# while debugging this wrapper you may wish to uncomment the following line
-	#printf "$text" >>"$HOME/tar_audit.txt";
+    text="\n";
+    text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
+    text="$text owner of $(echo \"$pwd\" | sed -e 's/%/%%/g') is: \"$owner\"\n";
+    text="$text $(echo $reportmsg | sed -e 's/%/%%/g')\n";
+    if [[ -n "$audit_text" ]]; then
+        text="$text error_code is: $error_code\n";
+        text="$text $(echo $audit_text | sed -e 's/%/%%/g')\n";
+        printf "$text" >>"$HOME/tar_errors.txt";
+    fi
+    if [[ "$ENABLE_WRAPPER_AUDIT" -eq 1 ]]; then
+        # log all tar commands actually run
+        printf "$text" >>"$HOME/tar_audit.txt";
+    fi
 }
+
+# An interesting issue arose when installing tcl8.6.0. The package is setting
+# a very restrictive umask for copy operations which resulted in the wrapper
+# creating read only temporary files, which caused the wrapper to fail.
+save_umask=$(umask);# backup the current umask
+umask 0077; # set a usable umask
 error_file=$(mktemp -t tar.XXXXXXXXXX);# temporary file for stderr output
+umask "$save_umask";# restore backed up umask
+
 $DAISY_CHAIN "$@" 2>"$error_file" || error_code="$?";
 ERROR=$(<"$error_file");
 $UNLINK_BYPASS "$error_file"; # remove temporary file
 echo "";# required for some reason to prevent false positive for $error_code
 if [[ "$error_code" -ne 0 ]]; then
-	if [[ "$owner" != "$me" ]]; then
-		echo "$pwd">>"$HOME/tar_owner_file_list.txt";
-		echo 1>&2 "*** The pwd: \"$pwd\"  is owned by  \"$owner\" and not \"$me\"";
-		echo 1>&2 "*** See the \"$HOME/tar_audit.txt\" file for details.";
-	fi
-	audit_text="ERROR: $ERROR";
-	echo "$ERROR" 1>&2;
+    if [[ "$owner" != "$me" ]]; then
+        echo "$pwd">>"$HOME/tar_owner_file_list.txt";
+        echo 1>&2 "*** The pwd: \"$pwd\"  is owned by  \"$owner\" and not \"$me\"";
+        echo 1>&2 "*** See the \"$HOME/tar_audit.txt\" file for details.";
+    fi
+    audit_text="ERROR: $ERROR";
+    echo "$ERROR" 1>&2;
 fi
 
 report_tar_useage;
diff --git a/lib/unlink b/lib/unlink
--- a/lib/unlink
+++ b/lib/unlink
@@ -7,17 +7,17 @@ DAISY_CHAIN="";
 me=$(whoami);
 reportmsg="unlink";
 for item in "$@"; do
-	regex="^.*['[:space:]].*$";
-	if [[ "$item" =~ $regex ]]; then
-	    regex="^(.*=)(.*['[:space:]].*)$";
-	    if [[ "$item" =~ $regex ]]; then
-			reportmsg="$reportmsg ${BASH_REMATCH[1]}\"${BASH_REMATCH[2]}\"";
-		else
-			reportmsg="$reportmsg \"$item\"";
-		fi
-	else
-		reportmsg="$reportmsg $item";
-	fi
+    regex="^.*['[:space:]].*$";
+    if [[ "$item" =~ $regex ]]; then
+        regex="^(.*=)(.*['[:space:]].*)$";
+        if [[ "$item" =~ $regex ]]; then
+            reportmsg="$reportmsg ${BASH_REMATCH[1]}\"${BASH_REMATCH[2]}\"";
+        else
+            reportmsg="$reportmsg \"$item\"";
+        fi
+    else
+        reportmsg="$reportmsg $item";
+    fi
 done
 
 for p in $(type -ap unlink) ; do
@@ -29,8 +29,15 @@ if [ -z "$DAISY_CHAIN" ]; then
   exit 1;
 fi
 
-if [ $UID -eq 0 ]; then
-  $DAISY_CHAIN "$@";
+error_code=0;
+if [[ $UID -eq 0 ]]; then
+  $DAISY_CHAIN "$@" || error_code="$?";
+  exit $error_code; #pass back any error code
+fi
+
+if [[ "$DISABLE_WRAPPERS" -eq 1 ]]; then
+  $DAISY_CHAIN "$@" || error_code="$?";
+  exit $error_code; #pass back any error code
 fi
 
 pwd=$(pwd);
@@ -39,72 +46,92 @@ error_code=0;
 audit_text="";
 
 report_owner_issues(){
-	text="\n";
-	text="$text ------file ownership issues-------------\n";
-	text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
-	text="$text $1\n";
-	printf "$text" >>"$HOME/unlink_owner_issues.txt";
+    text="\n";
+    text="$text ------file ownership issues-------------\n";
+    text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
+    text="$text $1\n";
+    printf "$text" >>"$HOME/unlink_owner_issues.txt";
+}
+report_errors(){
+    text="\n";
+    text="$text ------unlink command syntax errors-------------\n";
+    text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
+    text="$text $(echo $reportmsg | sed  -e 's/%/%%/g')\n";
+    text="$text $1\n";
+    printf "$text" >>"$HOME/unlink_syntax_errors.txt";
 }
 unlink_audit_log(){
-	text="\n";
-	text="$text ------ original command -------------\n";
-	text="$text $(echo $reportmsg | sed -e 's/%/%%/g')\n";
-	text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
-	text="$text ------ one of the resulting commands actually run -------\n";
-	text="$text $1";
-	if [[ -n "$audit_text" ]]; then
-		text="$text error_code is: $error_code\n";
-		text="$text $(echo $audit_text | sed -e 's/%/%%/g')\n";
-		printf "$text" >>"$HOME/unlink_errors.txt";
-	fi
-	# while debugging this wrapper you may wish to uncomment the following line
-	#printf "$text" >>"$HOME/unlink_audit.txt";
+    text="\n";
+    text="$text ------ original command -------------\n";
+    text="$text $(echo $reportmsg | sed -e 's/%/%%/g')\n";
+    text="$text present working directory is: $(echo \"$pwd\" | sed -e 's/%/%%/g')\n";
+    text="$text ------ one of the resulting commands actually run -------\n";
+    text="$text $1";
+    if [[ -n "$audit_text" ]]; then
+        text="$text error_code is: $error_code\n";
+        text="$text $(echo $audit_text | sed -e 's/%/%%/g')\n";
+        printf "$text" >>"$HOME/unlink_errors.txt";
+    fi
+    if [[ "$ENABLE_WRAPPER_AUDIT" -eq 1 ]]; then
+        # log all unlink commands actually run
+        printf "$text" >>"$HOME/unlink_audit.txt";
+    fi
 }
 
 # Syntax
 # unlink FILE
 # There is only one parameter for this command and it is likely a file or link
 
+# An interesting issue arose when installing tcl8.6.0. The package is setting
+# a very restrictive umask for copy operations which resulted in the wrapper
+# creating read only temporary files, which caused the wrapper to fail.
+save_umask=$(umask);# backup the current umask
+umask 0077; # set a usable umask
 error_file=$(mktemp -t unlink.XXXXXXXXXX);# temporary file for stderr output
+umask "$save_umask";# restore backed up umask
 
 # Note: because of our "for" loop, we could process more than one file on the
 # command line which is something the unlink command can not normally support.
 # This "for" loop manages to process filenames or paths with white space or 
 # special characters.
 for item in "$@"; do
-	error_code=0;
-	audit_text="";
-	if [[ -d "$item" ]]; then
-		# unlink is not supposed to be used on a directory
-		echo 1>&2 "*** ERROR: \"$item\" is a directory, unlink can not remove a directory.";
-		$DAISY_CHAIN "$error_file"; # remove temporary file
-		exit 0;
-	else
-		owner=$(stat -c%U -- "$item");
-		object="file or link";
-	fi
-	if [[ "$owner" != "$me" ]]; then
-		echo 1>&2 "*** The $object: \"$item\"  is owned by \"$owner\" and not \"$me\"";
-		echo 1>&2 "*** See the \"$HOME/unlink_owner_issues.txt\" file for details";
-		error_text="The $object: $(echo \"$item\" | sed -e 's/%/%%/g') is owned by \"$owner\" and not \"$me\"\n";
-		error_text="$error_text$DAISY_CHAIN $(echo \"$item\" | sed -e 's/%/%%/g')\n";
-		report_owner_issues "$error_text";
-		regex2="^[^/].*$"; # should only match if it is not a real full path
-		if [[ "$item" =~ $regex2 ]]; then
-			echo "$pwd/$item">>"$HOME/unlink_owner_file_list.txt";
-		else
-			echo "$item">>"$HOME/unlink_owner_file_list.txt";
-		fi
-	else
-		$DAISY_CHAIN "$item" 2>"$error_file" || error_code="$?";
-		ERROR=$(<"$error_file");		
-		if [[ "$error_code" -ne 0 ]]; then
-			audit_text="ERROR: $ERROR";	
-			echo "$ERROR" 1>&2; # output to stdout and stderr
-			pass_error="$error_code";
-		fi
-		unlink_audit_log "$DAISY_CHAIN $(echo \"$item\" | sed -e 's/%/%%/g')\n";
-	fi
+    error_code=0;
+    audit_text="";
+    if [[ -d "$item" ]]; then
+        # unlink is not supposed to be used on a directory
+        echo 1>&2 "*** ERROR: \"$item\" is a directory, unlink can not remove a directory.";
+        echo 1>&2 "*** See the \"$HOME/unlink_syntax_errors.txt\" file for details";
+        error_text="ERROR: $(echo \"$item\" | sed  -e 's/%/%%/g') is a directory,\n";
+        error_text="$error_text unlink can not remove a directory.\n";
+        report_errors "$error_text";
+        $DAISY_CHAIN "$error_file"; # remove temporary file
+        exit 0;
+    else
+        owner=$(stat -c%U -- "$item");
+        object="file or link";
+    fi
+    if [[ "$owner" != "$me" ]]; then
+        echo 1>&2 "*** The $object: \"$item\"  is owned by \"$owner\" and not \"$me\"";
+        echo 1>&2 "*** See the \"$HOME/unlink_owner_issues.txt\" file for details";
+        error_text="The $object: $(echo \"$item\" | sed -e 's/%/%%/g') is owned by \"$owner\" and not \"$me\"\n";
+        error_text="$error_text$DAISY_CHAIN $(echo \"$item\" | sed -e 's/%/%%/g')\n";
+        report_owner_issues "$error_text";
+        regex2="^[^/].*$"; # should only match if it is not a real full path
+        if [[ "$item" =~ $regex2 ]]; then
+            echo "$pwd/$item">>"$HOME/unlink_owner_file_list.txt";
+        else
+            echo "$item">>"$HOME/unlink_owner_file_list.txt";
+        fi
+    else
+        $DAISY_CHAIN "$item" 2>"$error_file" || error_code="$?";
+        ERROR=$(<"$error_file");        
+        if [[ "$error_code" -ne 0 ]]; then
+            audit_text="ERROR: $ERROR"; 
+            echo "$ERROR" 1>&2; # output to stdout and stderr
+            pass_error="$error_code";
+        fi
+        unlink_audit_log "$DAISY_CHAIN $(echo \"$item\" | sed -e 's/%/%%/g')\n";
+    fi
 done
 $DAISY_CHAIN "$error_file"; # remove temporary file
 exit "$pass_error";
